C++ ODBC Wrapper: ps::odbc::OdbcWrapper Class Reference
ps::odbc::OdbcWrapper Class Reference
Provides a high-level wrapper for ODBC operations.
#include <odbcwrapper.h>
Public Member Functions
bool connect (const std::wstring &dsn, const std::wstring &user, const std::wstring &password)
Establishes a connection to the database.
void disconnect ()
Disconnects from the database and releases the connection handle.
bool executeQuery (const std::wstring &query)
Executes a SQL query that retrieves data.
bool executeUpdate (const std::wstring &query)
Executes a SQL query that modifies data.
std::vector< std::vector< std::wstring > > fetchResults ()
Fetches the results of the last executed query.
SQLHDBC getHDbc () const
Retrieves the ODBC connection handle.
SQLHENV getHEnv () const
Retrieves the ODBC environment handle.
SQLHSTMT getHStmt () const
Retrieves the ODBC statement handle.
OdbcInterface * getOdbcInterface () const
Retrieves the ODBC interface implementation.
void initialize ()
Initializes the ODBC environment and allocates necessary handles.
bool isConnected () const
Checks if the database connection is active.
OdbcWrapper (std::unique_ptr< OdbcInterface > odbcImpl=nullptr)
Constructs an OdbcWrapper object.
~OdbcWrapper ()
Destroys the OdbcWrapper object and releases resources.
Private Member Functions
void handleError (SQLHANDLE handle, SQLSMALLINT handleType, SQLRETURN retCode)
Handles ODBC errors by retrieving diagnostic information.
Private Attributes
bool m_connected = false
Indicates whether the connection is active.
SQLHDBC m_hDbc = SQL_NULL_HDBC
ODBC connection handle.
SQLHENV m_hEnv = SQL_NULL_HENV
ODBC environment handle.
SQLHSTMT m_hStmt = SQL_NULL_HSTMT
ODBC statement handle.
std::unique_ptr< OdbcInterface > m_odbc = nullptr
Pointer to the ODBC interface implementation.
Detailed Description
Provides a high-level wrapper for ODBC operations.
This class simplifies the use of ODBC by managing handles, connections, and queries, while providing an interface for executing SQL commands and retrieving results.
Definition at line 20 of file odbcwrapper.h.
Constructor & Destructor Documentation
OdbcWrapper()
ps::odbc::OdbcWrapper::OdbcWrapper (std::unique_ptr< OdbcInterface > odbcImpl = nullptr)
Constructs an OdbcWrapper object.
Parameters
odbcImpl A unique pointer to an ODBC interface implementation. Defaults to nullptr.
Definition at line 11 of file odbcwrapper.cpp.
References ps::odbc::OdbcLogger::logInfo().
~OdbcWrapper()
ps::odbc::OdbcWrapper::~OdbcWrapper ()
Destroys the OdbcWrapper object and releases resources.
Definition at line 17 of file odbcwrapper.cpp.
References disconnect(), ps::odbc::OdbcLogger::logInfo(), m_hDbc, m_hEnv, m_hStmt, and m_odbc.
Member Function Documentation
connect()
bool ps::odbc::OdbcWrapper::connect (const std::wstring & dsn, const std::wstring & user, const std::wstring & password)
Establishes a connection to the database.
Parameters
dsn The Data Source Name (DSN) for the database.
user The username for authentication.
password The password for authentication.
Returns
True if the connection is successful, false otherwise.
Definition at line 99 of file odbcwrapper.cpp.
References handleError(), ps::odbc::OdbcLogger::logInfo(), m_connected, m_hDbc, m_hStmt, and m_odbc.
disconnect()
void ps::odbc::OdbcWrapper::disconnect ()
Disconnects from the database and releases the connection handle.
Definition at line 123 of file odbcwrapper.cpp.
References ps::odbc::OdbcLogger::logInfo(), m_connected, m_hDbc, m_hStmt, and m_odbc.
Referenced by ~OdbcWrapper().
executeQuery()
bool ps::odbc::OdbcWrapper::executeQuery (const std::wstring & query)
Executes a SQL query that retrieves data.
Parameters
query The SQL query to execute.
Returns
True if the query executes successfully, false otherwise.
Definition at line 143 of file odbcwrapper.cpp.
References handleError(), ps::odbc::OdbcLogger::logInfo(), m_connected, m_hStmt, and m_odbc.
executeUpdate()
bool ps::odbc::OdbcWrapper::executeUpdate (const std::wstring & query)
Executes a SQL query that modifies data.
Parameters
query The SQL query to execute.
Returns
True if the query executes successfully, false otherwise.
Definition at line 192 of file odbcwrapper.cpp.
References handleError(), ps::odbc::OdbcLogger::logInfo(), m_connected, m_hStmt, and m_odbc.
fetchResults()
std::vector< std::vector< std::wstring > > ps::odbc::OdbcWrapper::fetchResults ()
Fetches the results of the last executed query.
Returns
A vector of rows, where each row is a vector of strings representing column values.
Definition at line 161 of file odbcwrapper.cpp.
References ps::odbc::OdbcLogger::logInfo(), m_connected, m_hStmt, and m_odbc.
getHDbc()
SQLHDBC ps::odbc::OdbcWrapper::getHDbc () const inline
Retrieves the ODBC connection handle.
Returns
The ODBC connection handle.
Definition at line 119 of file odbcwrapper.h.
References m_hDbc.
getHEnv()
SQLHENV ps::odbc::OdbcWrapper::getHEnv () const inline
Retrieves the ODBC environment handle.
Returns
The ODBC environment handle.
Definition at line 112 of file odbcwrapper.h.
References m_hEnv.
getHStmt()
SQLHSTMT ps::odbc::OdbcWrapper::getHStmt () const inline
Retrieves the ODBC statement handle.
Returns
The ODBC statement handle.
Definition at line 126 of file odbcwrapper.h.
References m_hStmt.
getOdbcInterface()
OdbcInterface * ps::odbc::OdbcWrapper::getOdbcInterface () const inline
Retrieves the ODBC interface implementation.
Returns
A pointer to the ODBC interface implementation.
Definition at line 105 of file odbcwrapper.h.
References m_odbc.
handleError()
void ps::odbc::OdbcWrapper::handleError (SQLHANDLE handle, SQLSMALLINT handleType, SQLRETURN retCode) private
Handles ODBC errors by retrieving diagnostic information.
Parameters
handle The ODBC handle where the error occurred.
handleType The type of the handle (e.g., environment, connection, statement).
retCode The return code from the ODBC function.
Definition at line 36 of file odbcwrapper.cpp.
References ps::odbc::OdbcLogger::logError(), ps::odbc::OdbcLogger::logInfo(), and m_odbc.
Referenced by connect(), executeQuery(), executeUpdate(), and initialize().
initialize()
void ps::odbc::OdbcWrapper::initialize ()
Initializes the ODBC environment and allocates necessary handles.
Definition at line 80 of file odbcwrapper.cpp.
References handleError(), ps::odbc::OdbcLogger::logInfo(), m_hDbc, m_hEnv, and m_odbc.
isConnected()
bool ps::odbc::OdbcWrapper::isConnected () const inline
Checks if the database connection is active.
Returns
True if connected, false otherwise.
Definition at line 98 of file odbcwrapper.h.
References m_connected.
Member Data Documentation
m_connected
bool ps::odbc::OdbcWrapper::m_connected = false private
Indicates whether the connection is active.
Definition at line 25 of file odbcwrapper.h.
Referenced by connect(), disconnect(), executeQuery(), executeUpdate(), fetchResults(), and isConnected().
m_hDbc
SQLHDBC ps::odbc::OdbcWrapper::m_hDbc = SQL_NULL_HDBC private
ODBC connection handle.
Definition at line 23 of file odbcwrapper.h.
Referenced by connect(), disconnect(), getHDbc(), initialize(), and ~OdbcWrapper().
m_hEnv
SQLHENV ps::odbc::OdbcWrapper::m_hEnv = SQL_NULL_HENV private
ODBC environment handle.
Definition at line 22 of file odbcwrapper.h.
Referenced by getHEnv(), initialize(), and ~OdbcWrapper().
m_hStmt
SQLHSTMT ps::odbc::OdbcWrapper::m_hStmt = SQL_NULL_HSTMT private
ODBC statement handle.
Definition at line 24 of file odbcwrapper.h.
Referenced by connect(), disconnect(), executeQuery(), executeUpdate(), fetchResults(), getHStmt(), and ~OdbcWrapper().
m_odbc
std::unique_ptr<OdbcInterface> ps::odbc::OdbcWrapper::m_odbc = nullptr private
Pointer to the ODBC interface implementation.
Definition at line 26 of file odbcwrapper.h.
Referenced by connect(), disconnect(), executeQuery(), executeUpdate(), fetchResults(), getOdbcInterface(), handleError(), initialize(), and ~OdbcWrapper().
The documentation for this class was generated from the following files:
/media/psanodiya/workspace/cpp/cpp-odbc-wrapper/include/odbccpp/odbcwrapper.h
/media/psanodiya/workspace/cpp/cpp-odbc-wrapper/src/odbcwrapper.cpp