C++ ODBC Wrapper: ps::odbc::OdbcLogger Class Reference
ps::odbc::OdbcLogger Class Reference
Provides logging functionality for the ODBC wrapper.
#include <odbclogger.h>
Static Public Member Functions
static void initialize (const std::string &logFilePath)
Initializes the logger with a specified log file path.
static void logError (const std::string &message)
Logs an error message.
static void logInfo (const std::string &message)
Logs an informational message.
Detailed Description
Provides logging functionality for the ODBC wrapper.
This class uses the spdlog library to log messages to a file and the console. It supports logging informational and error messages.
Definition at line 19 of file odbclogger.h.
Member Function Documentation
initialize()
static void ps::odbc::OdbcLogger::initialize (const std::string & logFilePath) inline static
Initializes the logger with a specified log file path.
Parameters
logFilePath The path to the log file where logs will be written.
Definition at line 26 of file odbclogger.h.
logError()
static void ps::odbc::OdbcLogger::logError (const std::string & message) inline static
Logs an error message.
Parameters
message The message to log.
Definition at line 48 of file odbclogger.h.
Referenced by ps::odbc::OdbcWrapper::handleError().
logInfo()
static void ps::odbc::OdbcLogger::logInfo (const std::string & message) inline static
Logs an informational message.
Parameters
message The message to log.
Definition at line 39 of file odbclogger.h.
Referenced by ps::odbc::OdbcWrapper::connect(), ps::odbc::OdbcWrapper::disconnect(), ps::odbc::OdbcWrapper::executeQuery(), ps::odbc::OdbcWrapper::executeUpdate(), ps::odbc::OdbcWrapper::fetchResults(), ps::odbc::OdbcWrapper::handleError(), ps::odbc::OdbcWrapper::initialize(), ps::odbc::OdbcWrapper::OdbcWrapper(), and ps::odbc::OdbcWrapper::~OdbcWrapper().
The documentation for this class was generated from the following file:
/media/psanodiya/workspace/cpp/cpp-odbc-wrapper/include/odbclogger.h